"""Phase 24.3 -- report freshness: fingerprinting the deterministic
context and locating an existing FinancialInsightReport worth reusing
instead of paying for a new AI call.

Unlike app.insights.cache (an in-memory, ephemeral TTL cache wrapped
around a cheap, request-time AI rewrite), this phase's "cache" IS the
FinancialInsightReport table itself -- durable, queryable, and shown to
the user directly (Last Generated / Refresh Analysis), generated by a
background job rather than inline in a request. There is no separate
in-memory layer here; the table is the only cache.
"""

import hashlib
import json
import os
from datetime import datetime, timedelta, timezone

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.financial_report_status import FinancialReportStatus
from app.models import FinancialInsightReport

# How long a completed report stays reusable before a fresh "generate"
# request pays for a new AI call again, even if the underlying data
# genuinely hasn't changed (a belt-and-suspenders staleness bound on top
# of the fingerprint check -- data could theoretically stay identical for
# a long time in an inactive organization, but the report should still
# read as "generated N hours/days ago," not silently stay authoritative
# forever). 24 hours by default -- generous for a daily-cadence executive
# report, unlike app.insights' 30-minute dashboard-narration TTL.
REPORT_TTL_SECONDS = int(os.environ.get("FINANCIAL_AI_REPORT_TTL_SECONDS", str(24 * 3600)))


def _aware(value: datetime) -> datetime:
    """SQLite returns naive datetimes even for DateTime(timezone=True)
    columns; Postgres returns aware ones -- same normalization every
    other file in this codebase comparing a DB-read datetime against
    datetime.now(timezone.utc) already duplicates locally (see
    app.services.organization_api_keys._aware for the precedent)."""
    return value if value.tzinfo is not None else value.replace(tzinfo=timezone.utc)


def _strip_generated_at(value):
    """Recursively removes every `generated_at` key, at any depth --
    each of the ~10 deterministic section responses insight_builder
    assembles (ExecutiveOverviewResponse, RevenueTrendsResponse, ...)
    carries its OWN `generated_at` timestamp, not just the top-level
    context dict, so a shallow strip at the top level alone would leave
    the fingerprint sensitive to wall-clock time via any of those nested
    timestamps -- defeating the entire point of fingerprinting by DATA,
    not by when it was computed."""
    if isinstance(value, dict):
        return {k: _strip_generated_at(v) for k, v in value.items() if k != "generated_at"}
    if isinstance(value, list):
        return [_strip_generated_at(v) for v in value]
    return value


def compute_source_fingerprint(context: dict) -> str:
    """sha256 of a canonical (sorted-key) JSON snapshot of the
    deterministic context actually fed to the AI, with every
    `generated_at` timestamp stripped at any depth (see
    _strip_generated_at) -- a wall-clock timestamp changes every call and
    would defeat the whole point of fingerprinting: this must reflect the
    underlying financial DATA changing, not merely time passing. Two
    calls built from identical underlying data always produce the same
    fingerprint, regardless of when each was computed."""
    stable = _strip_generated_at(context)
    raw = json.dumps(stable, sort_keys=True, default=str)
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()


def compute_expires_at(*, now: datetime) -> datetime:
    return now + timedelta(seconds=REPORT_TTL_SECONDS)


def get_latest_report(db: Session, organization_id: str) -> FinancialInsightReport | None:
    """The most recent report row regardless of status -- what "Last
    Generated" / a pending background-job indicator / a past failure is
    rendered from. Never filtered to completed-only: a pending or failed
    row is exactly what the frontend needs to show its own loading/error
    state."""
    return db.scalar(
        select(FinancialInsightReport)
        .where(FinancialInsightReport.organization_id == organization_id)
        .order_by(FinancialInsightReport.created_at.desc())
        .limit(1)
    )


def find_reusable_report(
    db: Session, organization_id: str, fingerprint: str, *, now: datetime
) -> FinancialInsightReport | None:
    """A COMPLETED report for this fingerprint that hasn't expired yet --
    "only regenerate when requested (and even then, only if this doesn't
    find anything), expired, or financial data changed" per this phase's
    own requirement. Returns None (never regenerate blindly, but never
    reuse something stale either) when no such row exists, the newest
    matching row has expired, or the newest matching row for this
    organization is itself pending/failed (a pending generation for the
    OLD fingerprint is not "the same report," it's superseded data)."""
    report = db.scalar(
        select(FinancialInsightReport)
        .where(
            FinancialInsightReport.organization_id == organization_id,
            FinancialInsightReport.source_fingerprint == fingerprint,
            FinancialInsightReport.status == FinancialReportStatus.completed.value,
        )
        .order_by(FinancialInsightReport.created_at.desc())
        .limit(1)
    )
    if report is None:
        return None
    if report.expires_at is not None and _aware(report.expires_at) <= now:
        return None
    return report
